title: Victor Nyabutiongera
email: victor@university.edu
description: >-
  Academic portfolio of Victor Nyabutiongera.
baseurl: ""
url: ""

# Use the minimal theme for GitHub Pages
theme: minima

# Build settings
markdown: kramdown

# Exclude files
exclude:
  - README.md
