baseURL = "https://ongevic.github.io/"
title = "Victor Nyabutiongera - Academic Portfolio"
theme = "hugo-resume"
languageCode = "en-us"

[module]
  [[module.imports]]
    path = "github.com/eddiewebb/hugo-resume"

enableRobotsTXT = true

# Add new sections and social media placeholders
sections = ["about", "research", "cv", "posters", "tutorials", "contact"]

[params]
  # Placeholder profile image path
  profileImage = "img/profile.jpg"

  # Show contact and social icons
  showContact = true
  showSocializations = true

  # Choose a green-based theme and font size
  theme_day = "emerald"
  font_size = "m"

  # Social media handles (placeholders)
  [[params.handles]]
    name = "Instagram"
    link = "https://instagram.com/your_username"
    icon = "instagram"

  [[params.handles]]
    name = "Facebook"
    link = "https://facebook.com/your_username"
    icon = "facebook"

  [[params.handles]]
    name = "LinkedIn"
    link = "https://linkedin.com/in/your_username"
    icon = "linkedin"
